version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: quizpoc-postgres
    environment:
      POSTGRES_DB: QUIZPOC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0Password1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: quizpoc-postgres-data
